AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Blog Posts Lambda API

Globals:
  Function:
    Runtime: java17
    MemorySize: 2048
    Timeout: 29

Resources:
  ApiPassengerCounts:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod

  BlogPostsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.prueba.bancooccidente.StreamLambdaHandler
      CodeUri: target/banco-occidente-0.0.1-SNAPSHOT-lambda-package.zip
      AutoPublishAlias: live
      SnapStart:
        ApplyOn: PublishedVersions
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  BlogPostsEndpoint:
    Description: API Gateway PassengerCounts Endpoint
    Value:
      Fn::Sub: https://${PassengerCountsApi}.execute-api.${AWS::Region}.amazonaws.com/prod/